// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuovaAPI.DataLayer;

#nullable disable

namespace NuovaAPI.DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240527104304_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("NuovaAPI.DataLayer.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdVetrina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProdotto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Prezzo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IdVetrina");

                    b.ToTable("Prodotto", (string)null);
                });

            modelBuilder.Entity("NuovaAPI.DataLayer.Entities.Vetrina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vetrina", (string)null);
                });

            modelBuilder.Entity("NuovaAPI.DataLayer.Entities.Prodotto", b =>
                {
                    b.HasOne("NuovaAPI.DataLayer.Entities.Vetrina", "Vetrina")
                        .WithMany("ProdottiInVetrina")
                        .HasForeignKey("IdVetrina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vetrina");
                });

            modelBuilder.Entity("NuovaAPI.DataLayer.Entities.Vetrina", b =>
                {
                    b.Navigation("ProdottiInVetrina");
                });
#pragma warning restore 612, 618
        }
    }
}
